version: "3"
services:
  db:
    image: mysql:5.7
    container_name: MySQLServiceDB
    ports:
      - "3306:3306"
    environment: 
      MYSQL_USER: cloudM
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./DB/dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  cloudapi:
    build: ./cloudApi
    image: cloud_api
    container_name: CloudApi
    command: python3 main.py
    ports: 
      - "5000-5000"
    environment: 
      MYSQLPASSWORD: test
    links:
      - db
    depends_on: 
      - db
    networks: 
      - default
    volumes:
      - ./DB/FileUsers:/db
volumes:
  persistent: