version: "1"
services:
  db:
    image: mysql:5.7
    container_name: MySQLServiceDB
    ports:
      - "3306:3306"
    environment: 
      MYSQL_USER: cloudM
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./DB:/DataBase
      - persistent:/var/lib/mysql
    networks:
      - default
volumes:
  persistent: